name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - 'Makefile'

jobs:
  release:
    name: Package and Publish Helm Chart
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push to gh-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0  # Update as needed

      - name: Build chart and index
        run: |
          make index

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged
          publish_branch: gh-pages